server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        #单节点的Nacos配置值
        #server-addr: localhost:8848
        #换成Nginx的1111端口，做集群环境
        server-addr: 127.0.0.1:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"